### ISSUE TITLE
Failed to make

### ISSUE THREAD

**Issue by bernardshen** [mellanox-hpc/libibprof#19]
I tried to compile the library. However, I get the following error message. Could you please give me some clue on how to solve this or what is going wrong?

  CC       core/ibv/ibprof_ibv.lo
In file included from core/ibv/ibprof_ibv.c:18:0:
/usr/include/infiniband/arch.h:37:2: warning: #warning "This header is obsolete." [-Wcpp]
 #warning "This header is obsolete."
  ^~~~~~~
core/ibv/ibprof_ibv.c: In function ‘ibv_open_device_handler’:
core/ibv/ibprof_ibv.c:754:13: error: ‘struct ibv_context_ops’ has no member named ‘query_port’; did you mean ‘_compat_query_port’?
   check_api(query_port);
             ^
core/ibv/ibprof_ibv.c:706:12: note: in definition of macro ‘check_api’
   ret->ops._func = ibv_module_context.mean.ibv_##_func;       \
            ^~~~~
In file included from core/ibv/ibprof_ibv.c:17:0:
core/ibv/ibprof_ibv.c: At top level:
core/ibv/ibprof_ibv.c:58:26: error: expected declaration specifiers or ‘...’ before ‘__builtin_constant_p’
   struct ibv_mr* TYPE ## ibv_reg_mr(struct ibv_pd *pd, void *addr, size_t length, int access) \
                          ^
core/ibv/ibprof_ibv.c:621:9: note: in expansion of macro ‘HAVE_IBV_REG_MR_FUNC’
         HAVE_IBV_REG_MR_FUNC(TYPE) \
         ^~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:841:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_PROTOTYPED’
 DECLARE_OPTION_FUNCTIONS_PROTOTYPED( )
 ^
In file included from core/ibv/ibprof_ibv.c:20:0:
core/ibv/ibprof_ibv.c: In function ‘NONEibv_query_port’:
core/ibv/ibprof_ibv.c:666:101: warning: passing argument 3 of ‘f’ from incompatible pointer type [-Wincompatible-pointer-types]
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:847:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(NONE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:666:101: note: expected ‘struct _compat_ibv_port_attr *’ but argument is of type ‘struct ibv_port_attr *’
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:847:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(NONE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c: At top level:
core/ibv/ibprof_ibv.c:846:24: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 #define PREFIX_NONE(x) NONE##x,
                        ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_NONE’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:847:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(NONE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:846:24: note: (near initialization for ‘ibv_NONE_funcs.ibv_query_port’)
 #define PREFIX_NONE(x) NONE##x,
                        ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_NONE’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:847:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(NONE)
 ^~~~~~~~~~~~~~
In file included from core/ibv/ibprof_ibv.c:20:0:
core/ibv/ibprof_ibv.c: In function ‘PROFibv_query_port’:
core/ibv/ibprof_ibv.c:666:101: warning: passing argument 3 of ‘f’ from incompatible pointer type [-Wincompatible-pointer-types]
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:850:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(PROF)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:666:101: note: expected ‘struct _compat_ibv_port_attr *’ but argument is of type ‘struct ibv_port_attr *’
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:850:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(PROF)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c: At top level:
core/ibv/ibprof_ibv.c:849:24: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 #define PREFIX_PROF(x) PROF##x,
                        ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_PROF’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:850:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(PROF)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:849:24: note: (near initialization for ‘ibv_PROF_funcs.ibv_query_port’)
 #define PREFIX_PROF(x) PROF##x,
                        ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_PROF’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:850:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(PROF)
 ^~~~~~~~~~~~~~
In file included from core/ibv/ibprof_ibv.c:20:0:
core/ibv/ibprof_ibv.c: In function ‘VERBOSEibv_query_port’:
core/ibv/ibprof_ibv.c:666:101: warning: passing argument 3 of ‘f’ from incompatible pointer type [-Wincompatible-pointer-types]
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:853:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(VERBOSE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:666:101: note: expected ‘struct _compat_ibv_port_attr *’ but argument is of type ‘struct ibv_port_attr *’
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:853:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(VERBOSE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c: At top level:
core/ibv/ibprof_ibv.c:852:27: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 #define PREFIX_VERBOSE(x) VERBOSE##x,
                           ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_VERBOSE’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:853:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(VERBOSE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:852:27: note: (near initialization for ‘ibv_VERBOSE_funcs.ibv_query_port’)
 #define PREFIX_VERBOSE(x) VERBOSE##x,
                           ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_VERBOSE’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:853:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(VERBOSE)
 ^~~~~~~~~~~~~~
In file included from core/ibv/ibprof_ibv.c:20:0:
core/ibv/ibprof_ibv.c: In function ‘TRACEibv_query_port’:
core/ibv/ibprof_ibv.c:666:101: warning: passing argument 3 of ‘f’ from incompatible pointer type [-Wincompatible-pointer-types]
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:856:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(TRACE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:666:101: note: expected ‘struct _compat_ibv_port_attr *’ but argument is of type ‘struct ibv_port_attr *’
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:856:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(TRACE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c: At top level:
core/ibv/ibprof_ibv.c:855:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 #define PREFIX_TRACE(x) TRACE##x,
                         ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_TRACE’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:856:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(TRACE)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:855:25: note: (near initialization for ‘ibv_TRACE_funcs.ibv_query_port’)
 #define PREFIX_TRACE(x) TRACE##x,
                         ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_TRACE’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:856:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(TRACE)
 ^~~~~~~~~~~~~~
In file included from core/ibv/ibprof_ibv.c:20:0:
core/ibv/ibprof_ibv.c: In function ‘ERRibv_query_port’:
core/ibv/ibprof_ibv.c:666:101: warning: passing argument 3 of ‘f’ from incompatible pointer type [-Wincompatible-pointer-types]
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:859:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(ERR)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:666:101: note: expected ‘struct _compat_ibv_port_attr *’ but argument is of type ‘struct ibv_port_attr *’
 BV, ibv_query_port, _compat_query_port, context, context, port_num, port_attr) }; \
                                                                     ^
core/ibv/ibprof_ibv.h:132:13: note: in definition of macro ‘FUNC_BODY_INT’
     ret = f(__VA_ARGS__);                                               \
             ^~~~~~~~~~~
core/ibv/ibprof_ibv.c:835:1: note: in expansion of macro ‘DECLARE_OPTION_FUNCTIONS_INLINE’
 DECLARE_OPTION_FUNCTIONS_INLINE(type) \
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:859:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(ERR)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c: At top level:
core/ibv/ibprof_ibv.c:858:23: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
 #define PREFIX_ERR(x) ERR##x,
                       ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_ERR’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:859:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(ERR)
 ^~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:858:23: note: (near initialization for ‘ibv_ERR_funcs.ibv_query_port’)
 #define PREFIX_ERR(x) ERR##x,
                       ^
core/ibv/ibprof_ibv.c:481:2: note: in expansion of macro ‘PREFIX_ERR’
  OP(ibv_query_port) \
  ^~
core/ibv/ibprof_ibv.c:544:2: note: in expansion of macro ‘OP_ON_MEMBERS_LIST’
  OP_ON_MEMBERS_LIST(PREFIX##_##TYPE) \
  ^~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:836:1: note: in expansion of macro ‘DECLARE_OPTION_STRUCT’
 DECLARE_OPTION_STRUCT(type)
 ^~~~~~~~~~~~~~~~~~~~~
core/ibv/ibprof_ibv.c:859:1: note: in expansion of macro ‘DECLARE_OPTION’
 DECLARE_OPTION(ERR)
 ^~~~~~~~~~~~~~
Makefile:588: recipe for target 'core/ibv/ibprof_ibv.lo' failed
make[2]: *** [core/ibv/ibprof_ibv.lo] Error 1
make[2]: Leaving directory '/home/bernard/rdma_exp/libibprof/src'
Makefile:532: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bernard/rdma_exp/libibprof'
Makefile:408: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lzx404243** [comment]
I got the same error, do you have any hint on how to resolve this?
